import Nav from "./(components)/Nav";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;

export const metadata = {
  title: "Ticketing App",
  description: "Generated by FlyntDenzel",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="border p-3 rounded-md m-3">
        <div className="flex flex-col h-screen max-h-screen">
          <Nav />
          <div className="flex-grow overflow-y-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
